wget -c --no-check-certificate "https://ruxcon.org.au/assets/2015/slides/2015-DNS-as-a-Defense-Vector.pdf"
wget -c --no-check-certificate "https://ruxcon.org.au/assets/2015/slides/High-Performance-Fuzzing.pptx"
wget -c --no-check-certificate "https://ruxcon.org.au/assets/2015/slides/iVote2015Ruxcon.ppt"
wget -c --no-check-certificate "https://ruxcon.org.au/assets/2015/slides/ruxcon-2016-dowd.pptx"
wget -c --no-check-certificate "https://ruxcon.org.au/assets/2015/slides/Broadcasting-your-attack-Security-testing-DAB-radio-in-cars.pdf"
wget -c --no-check-certificate "https://ruxcon.org.au/assets/2015/slides/Windows 10, 2 Steps Forward, 1 Step Back - Redacted.pdf"
wget -c --no-check-certificate "https://ruxcon.org.au/assets/2015/slides/RUXCON15-Vitaly.pdf"
wget -c --no-check-certificate "https://ruxcon.org.au/assets/2015/slides/soho-RUXCON-2015-withoutvideo.pptx"
wget -c --no-check-certificate "https://ruxcon.org.au/assets/2015/slides/Ruxcon 2015 - McCormack.pdf"
wget -c --no-check-certificate "https://ruxcon.org.au/assets/2015/slides/sdn-201510-ruxcon.pdf"
wget -c --no-check-certificate "https://ruxcon.org.au/assets/2015/slides/Windows drivers attack surface.pptx"
wget -c --no-check-certificate "https://ruxcon.org.au/assets/2015/slides/javascript-Presentation.pptx"
wget -c --no-check-certificate "https://ruxcon.org.au/assets/2015/slides/High-Def Fuzzing Ruxcon2015.pdf"
wget -c --no-check-certificate "https://ruxcon.org.au/assets/2015/slides/VoIPWars-DestroyingJarJarLync-Filtered.pdf"
wget -c --no-check-certificate "https://ruxcon.org.au/assets/2015/slides/VENOM - Ruxcon.zip"
wget -c --no-check-certificate "https://ruxcon.org.au/assets/2015/slides/YummyYummyFruitSalad_Ruxcon2015_PeterFillmore.pdf"
wget -c --no-check-certificate "https://ruxcon.org.au/assets/2015/slides/rucon-bluecoat-rigo.pdf"
wget -c --no-check-certificate "https://ruxcon.org.au/assets/2015/slides/ruxcon-2015-automated_malware_analysis.ppt"
wget -c --no-check-certificate "https://ruxcon.org.au/assets/2015/slides/taco-jjones-ruxcon.pdf"
wget -c --no-check-certificate "https://ruxcon.org.au/assets/2015/slides/uaf-Ruxcon2015.pdf"
wget -c --no-check-certificate "https://ruxcon.org.au/assets/2015/slides/ruxcon2015-kario-slides-04.pdf"
wget -c --no-check-certificate "https://ruxcon.org.au/assets/2015/slides/Virtual-Machiene-Introspection.pptx"
